##########################################################################
# Copyright (c) 2019 NVIDIA Corporation. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# File: DL4AGX/toolchains/BUILD
# Description: Manage the difference between versions of PDKs 
############################################################################

# constaint_setting(name = "gcc_version")

# constraint_value(
#     name = "gcc_5.4",
#     constaint_setting = ":gcc_version"
# )

# constraint_value(
#     name = "gcc_7.4",
#     constaint_setting = ":gcc_version"
# )

# constaint_setting(name = "qnx_version")

# constraint_value(
#     name = "qnx_7.0.0",
#     constaint_setting = ":qnx_version"
# )

# platform(
#     name = "drive_pdk_5.1.3.0+linux",
#     constaint_values = {
#         "@platforms//os:linux",
#         "@platforms//cpu:aarch64",
#         ":gcc_5.4",
#     ],
# )

# platform(
#     name = "drive_pdk_5.1.6.0+linux",
#     constaint_values = {
#         "@platforms//os:linux",
#         "@platforms//cpu:aarch64",
#         ":gcc_7.4",
#     ],
# )

# platform(
#     name = "drive_pdk_5.1.3.0+qnx",
#     constaint_values = {
#         "@platforms//os:qnx",
#         "@platforms//cpu:aarch64",
#         ":qnx_7.0.0"
#     ],
# )

# platform(
#     name = "drive_pdk_5.1.6.0+qnx",
#     constaint_values = {
#         "@platforms//os:qnx",
#         "@platforms//cpu:aarch64",
#         ":qnx_7.0.0"
#     ],
# )
