iterations: 10

inputs:
        
        - name: cityscape
          type: image
          path: /home/nvidia/workspace/boyin/DL4AGX/mtmi/tests
          extension: .png


instances:
        - name: mtmi-backbone
          engine: engines/mtmi_encoder_fp16_gpu.plan
          core: -1
          inputs:
                  - name: input
                    sources:
                            - cityscape
                    shape: [1, 3, 1024, 1024]
          outputs:
                  - name: input.72
                    shape: [1, 32, 256, 256]
                  - name: input.148
                    shape: [1, 64, 128, 128]
                  - name: input.224
                    shape: [1, 160, 64, 64]
                  - name: input.292
                    shape: [1, 256, 32, 32]
          streamID: 0


seg_dla_path: engines/mtmi_seg_i8_dla.bin
depth_dla_path: engines/mtmi_depth_i8_dla.bin