iterations: 1

inputs:
        
        - name: cityscape
          type: image
          path: /home/nvidia/workspace/boyin/DL4AGX/mtmi/tests
          extension: .png


instances:
        - name: mtmi-backbone
          engine: mtmi_full.plan
          core: -1
          inputs:
                  - name: input
                    sources:
                            - cityscape
                    shape: [1, 3, 1024, 1024]
          outputs:
                  - name: 1966
                    shape: [1,1,1024,1024]
                  - name: output
                    shape: [1,1,1024,1024]
          streamID: 0

seg_dla_path: engines/mtmi_seg_i8_dla.bin
depth_dla_path: engines/mtmi_depth_i8_dla.bin