# ubuntu: 20.04
# cuda: 11.8
# torch: 1.14
FROM nvcr.io/nvidia/pytorch:22.12-py3

RUN chmod -R 777 /tmp
RUN apt update
RUN apt install libgl1-mesa-glx libsm6 libxext6  -y
RUN MMCV_WITH_OPS=1 FORCE_CUDA=1 pip install mmcv-full==1.6.0 mmdet==2.28.2 mmsegmentation==0.30.0 mmdet3d==1.0.0rc6

RUN pip install debugpy
RUN pip install numpy==1.23 opencv-python-headless==4.2.0.34
RUN pip install pycuda
RUN pip install onnx onnxruntime onnx_graphsurgeon onnxsim --extra-index-url https://pypi.ngc.nvidia.com
RUN pip install einops

# verify installation
RUN python -c "import cv2"
RUN python -m torch.utils.collect_env

